notify = ["bash", "/Users/simon/dotfiles/notify-osc9.sh"]

model = "gpt-5.3-codex"
model_reasoning_effort = "medium"
personality = "pragmatic"

[projects."/Users/simon/code/SymbolicRegression.jl"]
trust_level = "trusted"

[projects."/Users/simon/code/fun"]
trust_level = "trusted"

[projects."/Users/simon/code/pushworld_bot"]
trust_level = "trusted"

[projects."/Users/simon/code/codearena/baselines/Agentless"]
trust_level = "trusted"

[projects."/Users/simon/code/codearena"]
trust_level = "trusted"

[projects."/Users/simon/Downloads"]
trust_level = "trusted"

[projects."/Users/simon/code/PySR"]
trust_level = "trusted"

[projects."/Users/simon/code/pysr_paper"]
trust_level = "trusted"

[projects."/Users/simon/dotfiles"]
trust_level = "trusted"

[projects."/Users/simon/code/youtube-to-text"]
trust_level = "trusted"

[projects."/Users/simon/Documents/Latex/CV"]
trust_level = "trusted"

[projects."/Users/simon/code/simonalford42.github.io"]
trust_level = "trusted"

[projects."/Users/simon/code/aesthetic-site"]
trust_level = "trusted"

[projects."/home/sca63/dotfiles"]
trust_level = "trusted"

[projects."/home/sca63/meta_sr"]
trust_level = "trusted"

[projects."/home/sca63/meta_sr_test"]
trust_level = "trusted"

[projects."/home/sca63"]
trust_level = "trusted"

[projects."/home/sca63/meta_sr_teset"]
trust_level = "trusted"

[projects."/home/sca63/meta_sr_2_12"]
trust_level = "trusted"

[projects."/home/sca63/meta_sr/meta_sr_v8"]
trust_level = "trusted"

[projects."/home/sca63/meta_sr/meta_sr_v9"]
trust_level = "trusted"

[notice.model_migrations]
gpt-5-codex = "gpt-5.2-codex"

[tui]
notifications = ["agent-turn-complete"]
notification_method = "osc9"
